### ISSUE TITLE
Does this project work?

### ISSUE THREAD

**Issue by katcom** [yacy/yacy_search_androidclient#3]
Hey, I am interested in a yacy client on android, which is also aimed by your project. Are you interested in continuing the development?

**Comment by bqv** [comment]
I think that's a no...

**Comment by marcnause** [comment]
Sorry, I did not receive and automatic e-mail about the issue. I have pretty much abandoned this project since I have not contributed to YaCy in years and I also lost track of the current state of Android development.

The app also has several problems (HTTPS with self signed certificates does not work, (very rare) random crashes, outdated architecture). 

I think an up to date version of a Yacy cleint on Android would be nice. Since getting search results from a YaCy instance requires just a HTTP GET and the result can be parsed from the XML or JSON result, maybe a clean start would result in a more beautiful program though.
